name: Build Halium System

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      VENDOR: xiaomi
      DEVICE: cannon
      ANDROID_ROOT: /home/runner/work/halium/
      WORK_ING: /home/runner/work/ubports-ci/ubports-ci

    steps:
    - uses: actions/checkout@v4

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git python3 python3-dev \
        python-is-python3
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "UBports Xiaomi Pad 4 CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"
        mkdir -p $ANDROID_ROOT

    - name: Maximize build space
      uses: easimon/maximize-build-space@v4
      with:
         root-reserve-mb: 1024
         swap-size-mb: 512
         build-mount-path: '$ANDROID_ROOT'

    - name: Downloading source code
      run: |
        source halium.env
        cd $ANDROID_ROOT
        repo init -u https://github.com/Halium/android -b halium-12.0 --depth=1
        mkdir -p $ANDROID_ROOT/.repo/local_manifests
        echo $PWD
        cp -a $WORK_ING/xiaomi_cannon.xml $ANDROID_ROOT/.repo/local_manifests/
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Build HAL
      run: |
        sudo apt-get install -y python-is-python2
        chmod +x build-hal.sh
        bash -x build-hal.sh
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@v4
      with:
        name: halium-boot image
        path: /home/runner/work/halium/out/target/product/clover/halium-boot.img

    - name : Upload system image
      uses: actions/upload-artifact@v4
      with:
         name: System image
         path: /home/runner/work/halium/out/target/product/clover/system.img


    - name : Upload vendor image
      uses: actions/upload-artifact@v4
      with:
         name: Vendor image
         path: /home/runner/work/halium/out/target/product/clover/vendor.img
